### ISSUE TITLE
Multiple Page Form?

### ISSUE THREAD

**Issue by andrewteg** [CalderaWP/custom-cf-field-validator#1]
I need to extend a processor I created with this to function on a multi page form. However, when I do this it does not run the pre_processor until I have submitted the entire form. It runs the default Caledara required per page and I need to have it run my custom pre_processor stuff per page too so I can get all the requirements right before proceeding.

Is there something I need to hook into besides pre_processor in order to run on a "Next Page" button?

**Comment by Shelob9** [comment]
I'm sorry but this isn't possible. Switching pages doesn't involve the server at all, it's all in the browser.

Changing a page in a multi-page form isn't a submission. All it does is validate the current page, hide it and show the next page. Those pages are all part of the same form HTML element .

Check out our connected forms add-on if you want multi-step forms that do submit between steps.

**Comment by andrewteg** [comment]
Thanks for this. Makes sense that it is all in the browser.   I guess I was trying to figure out if there is a way to add my own validation to validate the current page.  Is that possible?

**Comment by Shelob9** [comment]
If you need to create a custom validator for a field, it should be possible.  The docs for Parsely, which is what we use cover this.
